### ISSUE TITLE
User Credentials not identified 

### ISSUE THREAD

**Issue by DeSailor** [chikorita157/malupdaterosx-cocoa#11]
I keep getting this: When I try to stream - 
![suk0m3k](https://cloud.githubusercontent.com/assets/11285397/8729856/92d046ba-2bbb-11e5-8492-3b5c4648111b.png)

I log in again, and it prompts again. And again. Won't allow me to detect streaming from Netflix, or CrunchyRoll. Also I tried once redownloading and that didn't help either.

**Comment by chikorita157** [comment]
It works fine for me. Please copy the console output by going to Console.app and filtering "MAL Updater OS X." You may need to logout and log back in.

Also, make sure the MAL API URL reads:
https://malapiv2.ateliershiori.moe

**Comment by chikorita157** [comment]
This seems to be an issue with the API, so I can't fix it in the client... I'll file a bug report with the API maintainer.
