### ISSUE TITLE
Cannot find titles (API change?)

### ISSUE THREAD

**Issue by indorilftw** [chikorita157/malupdaterosx-cocoa#13]
Cannot detect any anime title, nor search for anything when trying to add exception.
Probably caused by a change in the API(?)

Console log (example with Noragami Aragoto)
```
MAL Updater OS X[1243]: Starting...
MAL Updater OS X[1243]: Check Exceptions List
MAL Updater OS X[1243]: Checking Auto Exceptions
MAL Updater OS X[1243]: =============
MAL Updater OS X[1243]: Scrobbling...
MAL Updater OS X[1243]: Finding AniID
MAL Updater OS X[1243]: Searching For Title
MAL Updater OS X[1243]: Error: Couldn't find title Noragami Aragoto. Please add an Anime Exception rule.
MAL Updater OS X[1243]: Scrobble Complete with Status Code: 51
MAL Updater OS X[1243]: =============
```

**Comment by chikorita157** [comment]
Actually, it's an issue with the API, which got fixed recently. I will go and update the scripts;

https://bitbucket.org/ratan12/atarashii-api/commits/ede040b45160d5798c82ff0bc664eb487dfe30a7
