### ISSUE TITLE
Is API down?

### ISSUE THREAD

**Issue by CapitanCode** [chikorita157/malupdaterosx-cocoa#14]
<img width="451" alt="2015-12-05 2 56 51" src="https://cloud.githubusercontent.com/assets/14824142/11604299/e5fbbc16-9afb-11e5-9d0a-ffed578b2e96.png">
<img width="454" alt="2015-12-05 2 56 29" src="https://cloud.githubusercontent.com/assets/14824142/11604300/ecb79b7e-9afb-11e5-8715-49e8db9c4604.png">

**Comment by chikorita157** [comment]
I was trying to get Let's Encrypt certificates, but apparently I got rate limited and never reenabled Cloudflare's, thus using the self-signed, which won't work with MAL Updater OS X. It should work again soon as I reenabled it.

If it doesn't work, try https://malapiv2.ateliershiori.moe
