### ISSUE TITLE
Crashes using Netflix, and does nothing for Hulu

### ISSUE THREAD

**Issue by DeSailor** [chikorita157/malupdaterosx-cocoa#6]
Hi there! Thank you for restarting the use of MAL Updater for OSX. It's been great so far. However, when I try to use it watch anime on Netflix, it crashes. And when I try to use it to watch anime on Hulu, it recognizes nothing, and thus does nothing. 

If you'd like, I post the crash report for netflix. 

Regards, 

Sailor

**Comment by chikorita157** [comment]
I would like the crash log and also the output. For the console output, type MAL Updater in the filter field in Console App, copy and paste.

Also, Hulu is not supported by the application since I do not have a Hulu Plus subscription.

**Comment by DeSailor** [comment]
Console: 

3/3/15 7:34:14.754 PM MAL Updater OS X[2891]: Starting Auto Scrobble.
3/3/15 7:39:14.776 PM MAL Updater OS X[2891]: Starting...
3/3/15 7:42:28.252 PM MAL Updater OS X[2891]: Starting...
3/3/15 7:42:29.685 PM MAL Updater OS X[2891]: An uncaught exception was raised
3/3/15 7:42:29.685 PM MAL Updater OS X[2891]: nil string argument
3/3/15 7:42:29.686 PM MAL Updater OS X[2891]: (
	0   CoreFoundation                      0x00007fff9a24166c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8cdb976e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff9a24151d +[NSException raise:format:] + 205
	3   OgreKit                             0x00000001021a278f -[OGPlainString initWithString:] + 92
	4   OgreKit                             0x00000001021a2858 +[OGPlainString stringWithString:] + 53
	5   OgreKit                             0x0000000102198fe0 -[OGRegularExpression replaceString:withString:options:range:replaceAll:numberOfReplacement:] + 54
	6   OgreKit                             0x0000000102198d3e -[OGRegularExpression replaceAllMatchesInString:withString:] + 110
	7   MAL Updater OS X                    0x00000001021103c1 -[Detection checkifTitleIgnored:] + 117
	8   MAL Updater OS X                    0x000000010211002b -[Detection detectStream] + 598
	9   MAL Updater OS X                    0x000000010210f55c +[Detection detectmedia] + 88
	10  MAL Updater OS X                    0x000000010210902b -[MyAnimeList detectmedia] + 40
	11  MAL Updater OS X                    0x0000000102108a9a -[MyAnimeList startscrobbling] + 22
	12  MAL Updater OS X                    0x00000001021050da __41-[MAL_Updater_OS_XAppDelegate firetimer:]_block_invoke + 331
	13  libdispatch.dylib                   0x00007fff8e326323 _dispatch_call_block_and_release + 12
	14  libdispatch.dylib                   0x00007fff8e321c13 _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x00007fff8e32488f _dispatch_root_queue_drain + 935
	16  libdispatch.dylib                   0x00007fff8e332fe4 _dispatch_worker_thread3 + 91
	17  libsystem_pthread.dylib             0x00007fff985f6637 _pthread_wqthread + 729
	18  libsystem_pthread.dylib             0x00007fff985f440d start_wqthread + 13
)
3/3/15 7:42:29.687 PM MAL Updater OS X[2891]: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'nil string argument'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff9a24166c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8cdb976e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff9a24151d +[NSException raise:format:] + 205
	3   OgreKit                             0x00000001021a278f -[OGPlainString initWithString:] + 92
	4   OgreKit                             0x00000001021a2858 +[OGPlainString stringWithString:] + 53
	5   OgreKit                             0x0000000102198fe0 -[OGRegularExpression replaceString:withString:options:range:replaceAll:numberOfReplacement:] + 54
	6   OgreKit                             0x0000000102198d3e -[OGRegularExpression replaceAllMatchesInString:withString:] + 110
	7   MAL Updater OS X                    0x00000001021103c1 -[Detection checkifTitleIgnored:] + 117
	8   MAL Updater OS X                    0x000000010211002b -[Detection detectStream] + 598
	9   MAL Updater OS X                    0x000000010210f55c +[Detection detectmedia] + 88
	10  MAL Updater OS X                    0x000000010210902b -[MyAnimeList detectmedia] + 40
	11  MAL Updater OS X                    0x0000000102108a9a -[MyAnimeList startscrobbling] + 22
	12  MAL Updater OS X                    0x00000001021050da __41-[MAL_Updater_OS_XAppDelegate firetimer:]_block_invoke + 331
	13  libdispatch.dylib                   0x00007fff8e326323 _dispatch_call_block_and_release + 12
	14  libdispatch.dylib                   0x00007fff8e321c13 _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x00007fff8e32488f _dispatch_root_queue_drain + 935
	16  libdispatch.dylib                   0x00007fff8e332fe4 _dispatch_worker_thread3 + 91
	17  libsystem_pthread.dylib             0x00007fff985f6637 _pthread_wqthread + 729
	18  libsystem_pthread.dylib             0x00007fff985f440d start_wqthread + 13
)
3/3/15 7:42:30.460 PM ReportCrash[2972]: Saved crash report for MAL Updater OS X[2891] version 2.2.3 (2.2.3) to /Users/Matt/Library/Logs/DiagnosticReports/MAL Updater OS X_2015-03-03-194230_MacBook-Air.crash

**Comment by DeSailor** [comment]
Crash Log: https://mega.co.nz/#!kt5FERBT!Iqoeor111Iz04oAx4jOOrVRa-8_dtqrsEDo551zRME0

**Comment by chikorita157** [comment]
It looks like it's crashing on the title ignore check due to the title being missing or something. Can you stream an episode on Netflix and run detectstream and paste the output. The stream detection executable is located in the resources bundle.

**Comment by DeSailor** [comment]
MacBook-Air:~ Matt$ /Applications/MAL\ Updater\ OS\ X.app/Contents/Resources/detectstream ; exit;
2015-03-03 20:52:59.791 detectstream[3236:127263] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSRegularExpression enumerateMatchesInString:options:range:usingBlock:]: nil argument'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff9a24166c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8cdb976e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff9a24151d +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff9bccec39 -[NSRegularExpression(NSMatching) enumerateMatchesInString:options:range:usingBlock:] + 232
	4   Foundation                          0x00007fff9bd29e1e -[NSRegularExpression(NSMatching) rangeOfFirstMatchInString:options:range:] + 139
	5   detectstream                        0x00000001078bc29e -[ezregex checkMatch:pattern:] + 128
	6   detectstream                        0x00000001078bdf9b +[MediaStreamParse checkSeason:] + 77
	7   detectstream                        0x00000001078bdb52 +[MediaStreamParse parse:] + 5184
	8   detectstream                        0x00000001078bc01e main + 96
	9   libdyld.dylib                       0x00007fff91ec25c9 start + 1
	10  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by chikorita157** [comment]
Are you using the HTML5 player in Netflix by any chance? I haven't investigated HTML5 since my development Macbook Pro does not support it and I only use the Silverlight plugin, it's only supported on Macs that have Intel HD 3000 Graphics or later. Also, I do not plan on installing Yosemite on my main computer since I don't like it that much. 

From the looks of it, it doesn't seem to find the encoded JSON data, unlike the Silverlight version. I will investigate it later on, but for now, I suggest disabling "Prefer HTML5 player instead of Silverlight" in the playback settings until I find a fix.

**Comment by DeSailor** [comment]
Yes, I am running it Silverlight free. Thanks for the help.

**Comment by DeSailor** [comment]
Thought you should know, that for the time being. There is no way to fall back on Yosemite. HTML 5 is default and I cannot force it to use Silverlight.

**Comment by chikorita157** [comment]
I figured it out as the JSON data is not Base64 encoded with the HTML5 player. This should be an easy fix.

**Comment by DeSailor** [comment]
That's good to hear. Should be a quick update if do you chose to update it now.

**Comment by chikorita157** [comment]
![screen shot 2015-03-03 at 11 08 10 pm](https://cloud.githubusercontent.com/assets/161183/6478122/40563ab4-c1fa-11e4-91c0-88650473ff93.png)
It's fixed and I tested it on my 2012 Macbook Pro. Will be added to the next release later this week.

**Comment by chikorita157** [comment]
Fixed with https://github.com/Atelier-Shiori/detectstream/commit/46ccf04ff29edd815b2881812a73ca95cc157506

**Comment by DeSailor** [comment]
Sweet, thank you. :+1:
